#import "@preview/physica:0.9.8": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, node, edge

#set page(numbering: "1")

== Introduction and Reduced De Rham Sequences

We work in an axisymmetric cylindrical 2D3V setting with the map
$
  vec(r, theta, z) |-> vec(r cos theta, r sin theta, z),
  quad det J = r.
$
Write the physical field in the orthonormal cylindrical basis as
$
  bold(E) = E_hat(r) bold(e)_r + E_hat(theta) bold(e)_theta + E_hat(z) bold(e)_z
  = E_hat(r) partial_r + E_hat(theta) partial_theta / r + E_hat(z) partial_z.
$
The corresponding contravariant components are
$
  E^r = E_hat(r), quad E^theta = E_hat(theta) / r, quad E^z = E_hat(z).
$
Using the metric tensor,
$
  E_i = g_(i j) E^j, quad E^flat = E_i dif x^i,
$
and in cylindrical coordinates
$
  g = diagonalmatrix(1, r^2, 1),
$
we obtain
$
  E_r = E^r, quad E_theta = r^2 E^theta, quad E_z = E^z,
$
so the associated 1-form is
$
  bold(E)^flat
  = E^r dif r + r^2 E^theta dif theta + E^z dif z
  = E_hat(r) dif r + r E_hat(theta) dif theta + E_hat(z) dif z.
$
This is the correct object for line integrals. The corresponding flux 2-form is
$
  beta = star#h(0em)bold(E)^flat
  = (r E_hat(r)) dif theta and dif z
  + E_hat(theta) dif z and dif r
  + (r E_hat(z)) dif r and dif theta,
$
and differentiating once more gives the density 3-form
$
  tau = dif beta = r (nabla dot bold(E)) dif r and dif theta and dif z.
$
Under axisymmetry, $partial_theta = 0$, so
$
  tau = [partial_r (r E_hat(r)) + partial_z (r E_hat(z))] dif r and dif theta and dif z.
$

The full de Rham chain is
$
  V^0 stretch(-->)^G V^1 stretch(-->)^C V^2 stretch(-->)^D V^3.
$
In the reduced setting it splits into two independent chains.

For a scalar $phi$,
$
  dif phi = partial_r phi dif r + partial_z phi dif z,
$
so only the poloidal components appear. Differentiating a general 1-form gives
$
  dif bold(E)^flat
  &= dif (E_hat(r) dif r + r E_hat(theta) dif theta + E_hat(z) dif z) \
  &= -partial_z (r E_hat(theta)) dif theta and dif z
   + (partial_z E_hat(r) - partial_r E_hat(z)) dif z and dif r
   + partial_r (r E_hat(theta)) dif r and dif theta.
$
Matching coefficients with the flux 2-form gives the toroidal component
$
  B_hat(theta) = partial_z E_hat(r) - partial_r E_hat(z),
$
which yields the poloidal chain

#align(center)[#box(stroke: black, inset: 4pt)[$
  phi
    stretch(-->)^display(hat(nabla))
    E_hat(r) dif r + E_hat(z) dif z
    stretch(-->)^display(hat(nabla)_p times)
    B_hat(theta) dif z and dif r.
$]]

The remaining coefficients give the poloidal magnetic field generated by the toroidal electric field:
$
  B_hat(r) = - partial_z E_hat(theta), quad
  B_hat(z) = 1/r partial_r (r E_hat(theta)).
$
Since these depend only on the toroidal electric component, while $tau$ depends only on the poloidal magnetic components, we obtain the toroidal chain
#align(center)[#box(stroke: black, inset: 4pt)[$
  (r E_hat(theta)) dif theta
  stretch(-->)^display(hat(nabla)_theta times)
  ((r B_hat(r)) dif theta and dif z + (r B_hat(z)) dif r and dif theta)
  stretch(-->)^display(hat(nabla) dot)
  tau.
$]]
We refer to these as the poloidal and toroidal chains.

== Axis Regularity Constraints

In the reduced space the logical map is simply
$
  F_(r z) : vec(r, z) -> vec(r, z),
$
so the only nontrivial singular behavior comes from axisymmetry at $r = 0$.

An axisymmetric scalar field must be the restriction of a smooth function of $(x, y, z)$ that is invariant under rotations about the $z$-axis. Therefore scalar and axial quantities depend on $(r^2, z)$ rather than on $(r, z)$ arbitrarily. In particular,
$
  f = phi, E_z, B_z, rho
$
must be even in $r$ and satisfy
$
  partial_r f(0, z) = 0.
$

For transverse directions,
$
  hat(e)_r = (cos theta, sin theta, 0) = (x/r, y/r, 0), quad
  hat(e)_theta = (-sin theta, cos theta, 0) = (-y/r, x/r, 0).
$
If a radial or toroidal vector had a nonzero value on the axis, its Cartesian value would depend on the angle, which breaks axisymmetry. Hence transverse components must vanish on the axis. Writing
$
  V_perp
  = a(x^2 + y^2, z) (x, y) + b(x^2 + y^2, z) (-y, x)
  = r a(r^2, z) hat(e)_r + r b(r^2, z) hat(e)_theta,
$
we see that transverse components are odd in $r$:
$
  V_r, V_theta = r V_1(z) + r^3 V_3(z) + r^5 V_5(z) + dots.
$
Thus
$
  v = E_r, E_theta, B_r, B_theta quad => quad v(0, z) = 0.
$
By contrast, scalar and axial quantities are even:
$
  V_z, phi, rho = V_0(z) + r^2 V_2(z) + r^4 V_4(z) + dots.
$

For the toroidal chain we store
$
  u = r E_hat(theta), quad p = r B_hat(r), quad q = r B_hat(z).
$
The physical constraints above imply
$
  u(0, z) = partial_r u(0, z) = 0, \
  p(0, z) = partial_r p(0, z) = 0, \
  q(0, z) = 0.
$
The derivative conditions on $u$ and $p$ are necessary because, for example, if
$
  partial_r u(0, z) = a(z) != 0,
$
then
$
  u(r, z) = a(z) r + cal(O)(r^2),
$
which would imply $E_hat(theta)(0, z) != 0$. No analogous restriction is needed for $q$, since $B_hat(z)$ may be nonzero on the axis.

== Spline Spaces

We use tensor-product spline spaces for the two reduced de Rham sequences:
$
  "poloidal" : &
  hat(W)_(p,h)^0 := SS_(p,p) (hat(Omega))
  stretch(-->)^display(hat(nabla))
  hat(W)_(p,h)^1 := vec(SS_(p-1,p) (hat(Omega)), SS_(p,p-1) (hat(Omega)))
  stretch(-->)^display(hat(nabla)_p times)
  hat(W)_(p,h)^2 := SS_(p-1,p-1) (hat(Omega)) \
  "toroidal" : &
  hat(W)_(theta,h)^1 := SS_(p,p) (hat(Omega))
  stretch(-->)^display(hat(nabla)_theta times)
  hat(W)_(theta,h)^2 := vec(SS_(p,p-1) (hat(Omega)), SS_(p-1,p) (hat(Omega)))
  stretch(-->)^display(hat(nabla) dot)
  hat(W)_(theta,h)^3 := SS_(p-1,p-1) (hat(Omega)).
$

The corresponding tensor-product bases are
$
  "poloidal"
  cases(
    hat(W)_(p,h)^0 & : hat(T)_(i j)^(p,0) (r, z) = B_i (r) B_j (z),
    hat(W)_(p,h)^1 & : hat(bold(T))_(i j)^(p,r) = display(vec(M_i (r) B_j (z), 0)) "and" hat(bold(T))_(i,j)^(p,z) = display(vec(0, B_i (r) M_j (z))),
    hat(W)_(p,h)^2 & : hat(T)_(i j)^(p,2) (r, z) = M_i (r) M_j (z),
  ) \
  "toroidal"
  cases(
    hat(W)_(theta,h)^1 & : hat(T)_(i j)^(theta,1) (r, z) = B_i (r) B_j (z),
    hat(W)_(theta, h)^2 & : hat(bold(T))_(i,j)^(theta,r) = display(vec(B_i (r) M_j (z), 0)) "and" hat(bold(T))_(i,j)^(theta,z) = display(vec(0, M_i (r) B_j (z))),
    hat(W)_(theta,h)^3 & : hat(T)_(i j)^(theta,3) (r, z) = M_i (r) M_j (z),
  ).
$

These unconstrained spaces contain coefficients whose axisymmetric extensions are not smooth at $r = 0$. Define
$
  cal(A)^cal(l) := {"RZ coefficient forms whose axisymmetric extension is smooth at" r = 0},
$
and the admissible spaces by
$
  hat(V)_(dot,h)^cal(l) := hat(W)_(dot,h)^cal(l) inter cal(A)^cal(l),
  quad dif hat(V)_(dot,h)^cal(l) subset.eq hat(V)_(dot,h)^cal(l + 1).
$
Explicitly,
$
  "poloidal" &
  cases(
    hat(V)_(p,h)^0 = {phi = sum_(i,j) phi_(i j) hat(T)_(i j)^(p,0) in hat(W)_(p,h)^0 : phi_(1j) - phi_(0j) = 0 quad forall j },
    hat(V)_(p,h)^1 = {bold(v) = sum_(i j) v_(i j)^r hat(bold(T))_(i j)^(p,r) + sum_(i,j) v_(i j)^z hat(bold(T))_(i j)^(p,z) in hat(W)_(p,h)^1 : v_(0j)^r = v_(1j)^z - v_(0j)^z = 0 quad forall j },
    hat(V)_(p,h)^2 = {f = sum_(i,j) f_(i j) hat(T)_(i j)^(p,2) in hat(W)_(p,h)^2 : f_(0 j) = 0 quad forall j}
  ) \
  "toroidal" &
  cases(
    hat(V)_(theta,h)^1 = {psi = sum_(i,j) psi_(i j) hat(T)_(i j)^(theta,1) in hat(W)_(theta,h)^1 : psi_(0j) = psi_(1j) = 0 quad forall j},
    hat(V)_(theta,h)^2 = {bold(w) = sum_(i, j) w_(i j)^r hat(bold(T))_(i j)^(theta,r) + sum_(i,j) w_(i j)^z hat(bold(T))_(i j)^(theta,z) in hat(W)_(theta,h)^2 : w_(0j)^r = w_(1j)^r = w_(0j)^z = 0 quad forall j},
    hat(V)_(theta,h)^3 = {p = sum_(i,j) p_(i j) hat(T)_(i j)^(theta,3) in hat(W)_(theta,h)^3 : p_(0j) = 0 quad forall j}
  ).
$

These coefficient constraints come directly from the axis regularity conditions. For the scalar space,
$
  partial_r phi
  = sum_(i,j) phi_(i j) B_j (z) partial_r B_i (r)
  = sum_(i,j) B_j (z) (phi_(i+1,j) - phi_(i j)) M_i (r),
$
using
$
  sum_(i=0)^(n_s - 1) phi_(i j) (M_(i-1) (r) - M_i (r))
  =
  sum_(i=0)^(n_s-2) (phi_(i+1,j) - phi_(i j)) M_i (r).
$
Thus
$
  partial_r phi (0, z)
  = sum_(i,j) B_j (z) (phi_(i+1,j) - phi_(i j)) M_i (0) = 0
  quad => quad
  phi_(1,j) - phi_(0,j) = 0.
$

For the poloidal 1-form space, the radial component is transverse while the axial component is axial, so
$
  v^r(0, z) = 0, quad partial_r v^z(0, z) = 0,
$
hence
$
  v_(0j)^r = 0, quad v_(1j)^z - v_(0j)^z = 0 quad forall j.
$

The toroidal constraints are derived in the same way from
$
  psi(0, z) = partial_r psi(0, z) = 0,
$
and from the corresponding conditions on the stored poloidal magnetic components.

These constraints are preserved by the reduced complexes. In particular,
$
  phi_(1 j) - phi_(0j) = 0
  => partial_r phi (0,z) = 0
  => (partial_r phi) (0,z) = 0, quad partial_r (partial_z phi) (0,z) = 0, quad f(0,z) = 0,
$
and similarly for the toroidal chain,
$
  psi_(0j) = psi_(1j) = 0
  => psi(0, z) = partial_r psi(0,z) = 0
  => partial_z partial_r psi(0,z) = 0
  => partial_r partial_z psi(0,z) + partial_z partial_r psi(0,z) = 0.
$

== Projections

#align(left)[
  === Poloidal Chain
  #diagram(
    node((1, 0), $H^1(hat(Omega))$, name: <h1>),
    node((2, 0), $H(hat(nabla)_p times, hat(Omega))$, name: <curl>),
    node((3, 0), $L^2(hat(Omega))$, name: <div>),
  
    node((0, 1), $hat(V)_(p,h)^0$, name: <v0>),
    node((1, 1), $hat(V)_(p,h)^1$, name: <v1>),
    node((2, 1), $hat(V)_(p,h)^2$, name: <v2>),
  
    node((1, 2), $hat(W)_(p,h)^0$, name: <w0>),
    node((2, 2), $hat(W)_(p,h)^1$, name: <w1>),
    node((3, 2), $hat(W)_(p,h)^2$, name: <w2>),
  
    edge(<h1>, <curl>, $hat(nabla)$, "->"),
    edge(<curl>, <div>, $hat(nabla)_p times$, "->"),
  
    edge(<h1>, <w0>, $Pi_W^(p,0)$, "->", bend: +40deg, label-side: right, label-pos: 25%),
    edge(<curl>, <w1>, $Pi_W^(p,1)$, "->", bend: +40deg, label-side: right, label-pos: 25%),
    edge(<div>, <w2>, $Pi_W^(p,2)$, "->", bend: +40deg, label-side: right, label-pos: 25%),
  
    edge(<h1>, <v0>, $Pi^(p,0)$, "->", bend: -10deg, label-side: center, label-pos: 35%),
    edge(<curl>, <v1>, $Pi^(p,1)$, "->", bend: -10deg, label-side: center, label-pos: 35%),
    edge(<div>, <v2>, $Pi^(p,1)$, "->", bend: -10deg, label-side: center, label-pos: 35%),
  
    edge(<w0>, <v0>, $P_p^0$, "->", label-side: center, bend: -10deg),
    edge(<w1>, <v1>, $P_p^1$, "->", label-side: center, bend: -10deg),
    edge(<w2>, <v2>, $P_p^2$, "->", label-side: center, bend: -10deg),
  
    edge(<v0>, <v1>, $hat(nabla)$, "->"),
    edge(<v1>, <v2>, $hat(nabla)_p times$, "->"),
  
    edge(<w0>, <w1>, $hat(nabla)$, "->"),
    edge(<w1>, <w2>, $hat(nabla)_p times$, "->"),
  )
]

#align(right)[
  === Toroidal Chain
  #diagram(
    node((1, 0), $H(hat(nabla)_theta times, hat(Omega))$, name: <h1>),
    node((2, 0), $H(hat(nabla) dot, hat(Omega))$, name: <h2>),
    node((3, 0), $L^2 (hat(Omega))$, name: <h3>),
  
    node((0, 1), $hat(V)_(theta,h)^1$, name: <v0>),
    node((1, 1), $hat(V)_(theta,h)^2$, name: <v1>),
    node((2, 1), $hat(V)_(theta,h)^3$, name: <v2>),
  
    node((1, 2), $hat(W)_(theta,h)^1$, name: <w0>),
    node((2, 2), $hat(W)_(theta,h)^2$, name: <w1>),
    node((3, 2), $hat(W)_(theta,h)^3$, name: <w2>),
  
    edge(<h1>, <h2>, $hat(nabla)_theta times$, "->"),
    edge(<h2>, <h3>, $hat(nabla) dot$, "->"),
  
    edge(<h1>, <w0>, $Pi_W^(theta,1)$, "->", bend: +40deg, label-side: right, label-pos: 25%),
    edge(<h2>, <w1>, $Pi_W^(theta,2)$, "->", bend: +40deg, label-side: right, label-pos: 25%),
    edge(<h3>, <w2>, $Pi_W^(theta,3)$, "->", bend: +40deg, label-side: right, label-pos: 25%),
  
    edge(<h1>, <v0>, $Pi^(theta,1)$, "->", bend: -10deg, label-side: center, label-pos: 35%),
    edge(<h2>, <v1>, $Pi^(theta,2)$, "->", bend: -10deg, label-side: center, label-pos: 35%),
    edge(<h3>, <v2>, $Pi^(theta,3)$, "->", bend: -10deg, label-side: center, label-pos: 35%),
  
    edge(<w0>, <v0>, $P_theta^1$, "->", label-side: center, bend: -10deg),
    edge(<w1>, <v1>, $P_theta^2$, "->", label-side: center, bend: -10deg),
    edge(<w2>, <v2>, $P_theta^3$, "->", label-side: center, bend: -10deg),
  
    edge(<v0>, <v1>, $hat(nabla)_theta times$, "->"),
    edge(<v1>, <v2>, $hat(nabla) dot$, "->"),
  
    edge(<w0>, <w1>, $hat(nabla)_theta times$, "->"),
    edge(<w1>, <w2>, $hat(nabla) dot$, "->"),
  )
]

=== *$Pi$* Operators

We need to first project from continuous space to spline space. We have
$
  Pi_W^cal(l) v in hat(W)_h^cal(l), quad hat(bold(sigma))^cal(l) (Pi_W^cal(l) v) = hat(bold(sigma))^cal(l) (v)
$
where degrees of freedom correspond to point values, line integrals, face integrals, cell integrals. Our DOF's are
$
  "poloidal" : cases(
    sigma_(i j)^(p,0) (phi) = phi (r_i, z_j),
    sigma_(i j)^(p,1,r) (bold(E)) = integral_(r_i)^(r_(i+1)) E_r (r, z_j) dif r\, wide
      sigma_(i j)^(p,1,z) (bold(E)) = integral_(z_j)^(z_(j+1)) E_z (r_i, z) dif z,
    sigma_(i j)^(p,2) (B_theta)  = integral_(r_i)^(r_(i+1)) integral_(z_j)^(z_(j+1)) B_theta (r,z) dif r dif z
  )
$
$
  "toroidal" : cases(
    sigma_(i j)^(theta,1) (E_theta) = 2 pi v_theta (r_i, z_j),
    sigma_(i j)^(theta,2,r) (bold(B)) = 2 pi integral_(z_j)^(z_(j+1)) B_r (r_i, z) dif z\, wide sigma_(i j)^(theta,2,z) (bold(B)) = 2 pi integral_(r_i)^(r_(i+1)) B_z (r, z_j) dif r,
    sigma_(i j)^(theta,3) (tau) = 2 pi integral_(r_i)^(r_(i+1)) integral_(z_j)^(z_(j+1)) tau (r,z) dif r dif z
  )
$
then we need
$
  Pi_W^(p,0) phi = sum_(k,j) c_(k l) B_k (r) B_l (z), quad sum_(k,j) c_(k l) B_k (r_i) B_l (z_j) = phi(r_i, z_j) \
  Pi_W^(p,1) bold(E) = sum_(k,l) vec(c_(k l)^r M_k (r) B_l (z), c_(k l)^z B_k (r) M_l (z)), quad
    sum_(k,l) vec(
      integral_(r_i)^(r_(i+1)) c_(k l)^r M_k (r) B_l (z_j) dif r,
      integral_(z_j)^(z_(j+1)) c_(k l)^z B_k (r_i) M_l (z) dif z
    ) = vec(
      integral_(r_i)^(r_(i+1)) E_r (r, z_j) dif r,
      integral_(z_j)^(z_(j+1)) E_z (r_i, z) dif z
    )
  \
  Pi_W^(p,2) B_theta = sum_(k,j) M_k (r) M_j (z), quad
  limits(integral)_(z_j)^(z_(j+1)) limits(integral)_(r_i)^(r_(i+1)) sum_(k,j) M_k (r) M_j (z) dif r dif z = limits(integral)_(z_j)^(z_(j+1)) limits(integral)_(r_i)^(r_(i+1)) B_theta (r,z) dif r dif z
$
and similar relations for the toroidal operators. These commute due to Stokes' theorem. Now to find the coefficients, let's take $Pi_W^(p,0)$
$
  Pi_W^(p,0) phi = sum_(k,j) c_(k l) B_k (r) B_l (z)
$
take knots $zeta_a^r, zeta_b^z$ in $r$ and $z$ directions, we have
$
  sum_(k,j) c_(k l) B_k (zeta_a^r) B_l (zeta_b^z) = phi(zeta_a^r, zeta_b^z) = s_(a b)
$
define collocation matrices
$
  K_r [a,i] = B_i (zeta_a^r), quad K_z [b,j] = B_j (zeta_b^r)
$
then
$
  K_r C K_z^T = S
$
so we solve
$
  K_r Y = S, quad K_z C^T = Y^T
$
same for the other operators. These $K$ matrices can be precomputed once at the start of the simulation, and with the inverses found the spline coefficients are easily computed. Greville points are used as nodes.

=== *$P$* Operators

We now construct projections from the unconstrained spline spaces onto the admissible spaces in a way that commutes with the reduced differential operators.

For the poloidal chain, the constraints are local in the first radial coefficients, so the projections are immediate:
$
  P_p^0 : hat(W)_(p,h)^0 -> hat(V)_(p,h)^0, quad cases(
    P_p^0 hat(T)_(0 j)^(p,0) := 0,
    P_p^0 hat(T)_(1 j)^(p,0) := hat(T)_(0 j)^(p,0) + hat(T)_(1 j)^(p,0),
    P_p^0 hat(T)_(i j)^(p,0) := hat(T)_(i j)^(p,0) quad forall (i >= 2),
  )
$
$
  P_p^1 : hat(W)_(p,h)^1 -> hat(V)_(p,h)^1, quad cases(
    P_p^1 hat(bold(T))_(0 j)^(p,r) := 0,
    P_p^1 hat(bold(T))_(i j)^(p,r) := hat(bold(T))_(i j)^(p,r) quad forall (i >= 1),
    P_p^1 hat(bold(T))_(0 j)^(p,z) := 0,
    P_p^1 hat(bold(T))_(1 j)^(p,z) := hat(bold(T))_(0 j)^(p,z) + hat(bold(T))_(1 j)^(p,z),
    P_p^1 hat(bold(T))_(i j)^(p,z) := hat(bold(T))_(i j)^(p,z) quad forall (i >= 2),
  )
$
$
  P_p^2 : hat(W)_(p,h)^2 -> hat(V)_(p,h)^2, quad cases(
    P_p^2 hat(T)_(0 j)^(p,2) := 0,
    P_p^2 hat(T)_(i j)^(p,2) := hat(T)_(i j)^(p,2) quad forall (i >= 1),
  ).
$

For the toroidal chain, the commuting requirement determines the nontrivial part of the construction:
$
  (hat(nabla)_theta times) P_theta^1 = P_theta^2 (hat(nabla)_theta times).
$
First note that
$
  hat(nabla)_theta times hat(T)_(i j)^(theta,1)
  = vec(
    - partial_z hat(T)_(i j)^(theta,1),
    partial_r hat(T)_(i j)^(theta,1)
  )
  = - hat(bold(T))_(i,j-1)^(theta,r) + hat(bold(T))_(i,j)^(theta,r) + hat(bold(T))_(i-1,j)^(theta,z) - hat(bold(T))_(i,j)^(theta,z).
$
The cases $i = 0$ and $i >= 2$ are straightforward, so the only delicate basis element is $hat(T)_(1 j)^(theta,1)$. To make the projection commute with the curl while also enforcing the toroidal constraints, we use a telescoping correction:
$
  P_theta^1 hat(T)_(1 j)^(theta,1) := - sum_(k=2)^(n_s-1) hat(T)_(k j)^(theta,1).
$
Then
$
  (hat(nabla)_theta times) P_theta^1 hat(T)_(1 j)^(theta,1)
  &=
    sum_(k=2)^(n_s-1) hat(bold(T))_(k,j-1)^(theta,r)
    - sum_(k=2)^(n_s-1) hat(bold(T))_(k,j)^(theta,r)
    - sum_(k=2)^(n_s-1) hat(bold(T))_(k-1,j)^(theta,z)
    + sum_(k=2)^(n_s-1) hat(bold(T))_(k,j)^(theta,z) \
  &=
    sum_(k=2)^(n_s-1) hat(bold(T))_(k,j-1)^(theta,r)
    - sum_(k=2)^(n_s-1) hat(bold(T))_(k,j)^(theta,r)
    - hat(bold(T))_(1,j)^(theta,z),
$
where the $z$-components telescope.

This determines the matching correction in $P_theta^2$:
$
  P_theta^2 hat(bold(T))_(1j)^(theta,r) := - sum_(k=2)^(n_s-1) hat(bold(T))_(k j)^(theta,r).
$
Indeed,
$
  P_theta^2 (hat(nabla)_theta times hat(T)_(1 j)^(theta,1))
  &= P_theta^2(
    - hat(bold(T))_(1,j-1)^(theta,r)
    + hat(bold(T))_(1,j)^(theta,r)
    + hat(bold(T))_(0,j)^(theta,z)
    - hat(bold(T))_(1,j)^(theta,z)
  ) \
  &=
    sum_(k=2)^(n_s-1) hat(bold(T))_(k,j-1)^(theta,r)
    - sum_(k=2)^(n_s-1) hat(bold(T))_(k,j)^(theta,r)
    - hat(bold(T))_(1,j)^(theta,z),
$
which matches the previous expression exactly.

Collecting the final toroidal projections,
$
  P_theta^1 : hat(W)_(theta,h)^1 -> hat(V)_(theta,h)^1, quad cases(
    P_theta^1 hat(T)_(0 j)^(theta,1) := 0,
    P_theta^1 hat(T)_(1 j)^(theta,1) := - sum_(k=2)^(n_s-1) hat(T)_(k j)^(theta,1),
    P_theta^1 hat(T)_(i j)^(theta,1) := hat(T)_(i j)^(theta,1) quad forall (i >= 2),
  )
$
$
  P_theta^2 : hat(W)_(theta,h)^2 -> hat(V)_(theta,h)^2, quad cases(
    P_theta^2 hat(bold(T))_(0 j)^(theta,r) := 0,
    P_theta^2 hat(bold(T))_(1j)^(theta,r) := - sum_(k=2)^(n_s-1) hat(bold(T))_(k j)^(theta,r),
    P_theta^2 hat(bold(T))_(i j)^(theta,r) := hat(bold(T))_(i j)^(theta,r) quad forall (i >= 2),
    P_theta^2 hat(bold(T))_(0 j)^(theta,z) := 0,
    P_theta^2 hat(bold(T))_(i j)^(theta,z) := hat(bold(T))_(i j)^(theta,z) quad forall (i >= 1),
  )
$
$
  P_theta^3 : hat(W)_(theta,h)^3 -> hat(V)_(theta,h)^3, quad cases(
    P_theta^3 hat(T)_(0 j)^(theta,3) := 0,
    P_theta^3 hat(T)_(i j)^(theta,3) := hat(T)_(i j)^(theta,3) quad forall (i >= 1),
  ).
$

For the second commuting relation,
$
  (hat(nabla) dot) P_theta^2 = P_theta^3 (hat(nabla) dot),
$
we use
$
  hat(nabla) dot hat(bold(T))_(i j)^(theta,r)
  = hat(nabla) dot vec(B_i (r) M_j (z), 0)
  = (M_(i-1) (r) - M_i (r)) M_j (z)
  = hat(T)_(i-1,j)^(theta,3) - hat(T)_(i,j)^(theta,3).
$
For the only nontrivial basis element,
$
  (hat(nabla) dot) P_theta^2 hat(bold(T))_(1j)^(theta,r)
  = - hat(nabla) dot (sum_(k=2)^(n_s-1) hat(bold(T))_(k j)^(theta,r))
  = sum_(k=2)^(n_s-1) (hat(T)_(k,j)^(theta,3) - hat(T)_(k-1,j)^(theta,3))
  = - hat(T)_(1,j)^(theta,3),
$
while
$
  P_theta^3 (hat(nabla) dot) hat(bold(T))_(1j)^(theta,r)
  = P_theta^3 (hat(T)_(0,j)^(theta,3) - hat(T)_(1,j)^(theta,3))
  = - hat(T)_(1,j)^(theta,3).
$
All remaining cases commute immediately from the definitions.

== Discrete Derivative Matrices

$
  hat(nabla) (B_i times.o B_j) = vec(
    (M_(i-1) - M_i) times.o B_j,
    B_i times.o (M_(j-1) - M_j)
  ), quad hat(nabla)_p times vec(
    a M_i times.o B_j,
    b B_i times.o M_j
  ) = a M_i times.o (M_(j-1) - M_j) - b (M_(i-1) - M_i) times.o M_j \
  hat(nabla)_theta times (B_i times.o B_j) = vec(
    - B_i times.o (M_(j-1) - M_j),
    (M_(i-1) - M_i) times.o B_j
  ), quad hat(nabla) dot vec(
    a B_i times.o M_j,
    b M_i times.o B_j
  ) = a (M_(i-1) - M_i) times.o M_j + b M_i (M_(j-1) - M_j)
$

Then we construct matrices
$
  & cal(G)_((r,l,k),(i,j)) = (delta_(l,i-1) - delta_(l,i)) delta_(k,j), quad && cal(G)_((z,l,k),(i,j)) = delta_(l,i) (delta_(k,j-1) - delta_(k,j)) \
  & cal(C)_((l,k),(r,i,j))^p = delta_(l,i) (delta_(k,j-1) - delta_(k,j)), quad && cal(C)_((l,k),(z,i,j))^p = - (delta_(l,i-1) - delta_(l,i)) delta_(k,j) \
  & cal(C)_((r,l,k),(i,j))^theta = - delta_(l,i) (delta_(k,j-1) - delta_(k,j)), quad && cal(C)_((z,l,k),(i,j))^theta = (delta_(l,i-1) - delta_(l,i)) delta_(k,j) \
  & cal(D)_((l,k),(r,i,j)) = (delta_(l,i-1) - delta_(l,i)) delta_(k,j), quad && cal(D)_((l,k),(z,i,j)) = delta_(l,i) (delta_(k,j-1) - delta_(k,j))
$
with indices
$
  cal(G) in RR^(cal(J)_h^(p,1) times cal(J)_h^(p,0)), quad cal(C)^p in RR^(cal(J)_h^(p,2) times cal(J)_h^(p,1)) \
  cal(C)^theta in RR^(cal(J)_h^(theta,2) times cal(J)_h^(theta,1)), quad cal(D) in RR^(cal(J)_h^(theta,3) times cal(J)_h^(theta,2))
$
$
  cal(J)_h^(p,0) &= {(i,j) : 0<= i < n_s, 0<= j < n_z} \
  cal(J)_h^(p,1) &= {(i,j) : 0 <= i < n_s - 1, 0<= j < n_z } union {(i,j) : 0 <= i < n_s, 0<= j < n_z - 1} \
  cal(J)_h^(p,2) &= {(i,j) : 0 <= i < n_s - 1, 0 <= j < n_z - 1}
$
$
  cal(J)_h^(theta,1) &= {(i,j) : 0 <= i < n_s, 0 <= j < n_z} \
  cal(J)_h^(theta,2) &= {(i,j) : 0 <= i < n_s, 0 <= j < n_z - 1 } union {(i,j) : 0 <= i < n_s - 1, 0<= j < n_z } \ 
  cal(J)_h^(theta,3) &= {(i,j) : 0 <= i < n_s - 1, 0 <= j < n_z - 1}
$

These can be verified to satisfy $cal(C)^p cal(G) = 0, cal(D) cal(C)^theta = 0$.

$
  hat(nabla) hat(T)_a^(p,0) = sum_mu cal(G)_(mu a) hat(bold(T))_mu^(p,1), quad hat(nabla)_p times hat(bold(T))_a^(p,1) = sum_mu cal(C)_(mu a)^p hat(T)_mu^(p,2) \
  hat(nabla)_theta times hat(T)_a^(theta,1) = sum_mu cal(C)_(mu a)^theta hat(bold(T))_mu^(theta,2), quad hat(nabla) dot hat(bold(T))_a^(theta,2) = sum_mu cal(D)_(mu a) hat(T)_mu^(theta,3) \
$

== Mass Matrices

Using index sets $mu = (i,j), nu = (k,l)$
#grid(
  columns: (1fr,) * 2,
  $
    cal(M)_(mu,nu)^(p,0) &= 2 pi integral_hat(Omega) hat(T)_mu^(p,0) hat(T)_nu^(p,0) med r dif r dif z \
    cal(M)_(mu,nu)^(p,1) &= 2 pi integral_hat(Omega) hat(bold(T))_mu^(p,1) dot hat(bold(T))_nu^(p,1) med r dif r dif z \
    cal(M)_(mu,nu)^(p,2) &= 2 pi integral_hat(Omega) hat(T)_mu^(p,2) hat(T)_nu^(p,2) med r dif r dif z \
  $,
  $
    cal(M)_(mu,nu)^(theta,1) &= 2 pi integral_hat(Omega) hat(T)_mu^(theta,1) hat(T)_nu^(theta,1) med 1/r dif r dif z \
    cal(M)_(mu,nu)^(theta,2) &= 2 pi integral_hat(Omega) hat(bold(T))_mu^(theta,2) dot hat(bold(T))_nu^(theta,2) med 1/r dif r dif z \
    cal(M)_(mu,nu)^(theta,3) &= 2 pi integral_hat(Omega) hat(T)_mu^(theta,3) hat(T)_nu^(theta,3) med 1/r dif r dif z \
  $
)

== Maxwell's Equations

Our fields are
#grid(
  columns: (1fr,) * 2,
  $
    r E_theta (r,z,t) &= sum_(i,j) e_(i j)^theta hat(T)_(i j)^(theta,1) \
    bold(E)^p (r,z,t) &= sum_(i,j) (e_(i j)^(p,r) hat(bold(T))_(i j)^(p,r) + e_(i j)^(p,z) hat(bold(T))_(i j)^(p,z))
  $,
  $
    B_theta (r,z,t) &= sum_(i,j) b_(i j)^theta hat(T)_(i j)^(p,2) \
    r bold(B)^theta (r,z,t) &= sum_(i,j) (b_(i j)^(theta,r) hat(bold(T))_(i j)^(theta,r) + b_(i,j)^(theta,z) hat(bold(T))_(i j)^(theta,z)) \
  $
)
Gauss's law
$
  - 2 pi integral_hat(Omega) hat(nabla) hat(T)_a^(p,0) (r,z) dot bold(E)^p (r,z,t) r dif r dif z = hat(rho) (hat(T)_a^(p,0)) \
  - sum_(mu, nu) cal(G)_(mu a) cal(M)_(mu nu)^(p,1) e_nu^p = hat(rho) (hat(T)_a^(p,0)) \
  cal(G)^T cal(M)^(p,1) bold(e)^p = -bold(rho)^0, quad bold(rho)_a^0 = sum_(p=1)^N_p q_p omega_p hat(T)_a^(p,0) (r_p, z_p)
$

Ampere's law (where $phi$ is a test function)
$
  integral_hat(Omega) phi dot partial_t bold(E) dif V = integral_hat(Omega) (nabla times phi) dot bold(B) dif V - J(phi)
$
then, where $phi_theta, E_theta, B_r, B_z$ represent physical field components
$
  2 pi integral_hat(Omega) phi_theta partial_t E_theta 1 / r dif r dif z + 2 pi integral_hat(Omega) bold(phi)^p dot partial_t bold(E)^p r dif r dif z \ = 2 pi integral_hat(Omega) (hat(nabla)_p times bold(phi)^p) B_theta r dif r dif z + 2 pi integral_hat(Omega) (hat(nabla)_theta times phi_theta) dot bold(B)^theta 1 / r dif r dif z - J(bold(phi)^p, phi_theta)
$
so discretely
$
  cal(M)^(p,1) dot(bold(e))^p &= (cal(C)^p)^T cal(M)^(p,2) bold(b)_theta - bold(j)^p \
  cal(M)^(theta,1) dot(bold(e))^theta &= (cal(C)^theta)^T cal(M)^(theta,2) bold(b)^p - bold(j)^theta \
$

Then Faraday's and magnetic Gauss' law are
$
  cal(C)^p bold(e)^p = - dot(bold(b))_theta, quad cal(C)^theta bold(e)^theta = - dot(bold(b))^p \
  cal(D) bold(b)^p = 0
$
